name: Trigger https://norns.community Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger https://norns.community Build
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh api repos/monome-community/norns-community/dispatches \
            --method POST \
            -f event_type=trigger_build_via_norns_community_merge \
            -f 'client_payload[unit]=false' \
            -f 'client_payload[integration]=true'
