name: "Trigger https://norns.community Build"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger_build_via_norns_community_merge:
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger https://norns.community Build"
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"event_type": "trigger_build_via_norns_community_merge"}' \
            https://api.github.com/repos/monome-community/norns-community/dispatches
